import json
import os,time
from smartapi import SmartWebSocket, SmartConnect
from PyQt5 import QtCore, QtGui, QtWidgets
from dotenv import load_dotenv

import sys
from thread import thread_with_trace
from stockIndices import getData



class Ui_Canis(object):
    def __init__(self):
        load_dotenv()
        CLIENT_CODE=os.getenv('Client_ID')
        PASSWORD=os.getenv('Password')
        API_KEY=os.getenv('API_key')
        # self.example = [{'e': 'nse_cm', 'ltp': '1955.20', 'ltq': '2', 'ltt': 'NA', 'name': 'sf', 'tk': '11483'}, {'c': '17757.00', 'cng': '-146.85', 'e': 'nse_cm', 'ltp': '17610', 'ltt': 'NA', 'name': 'sf', 'nc': '-00.827', 'tk': '26000'}, {'c': '37850.85', 'cng': '-313.65', 'e': 'nse_cm', 'ltp': '37537.20', 'ltt': 'NA', 'name': 'sf', 'nc': '-00.8286', 'tk': '26009'}]

        obj=SmartConnect(api_key=API_KEY)
        obj.generateSession(CLIENT_CODE,PASSWORD)
        FEED_TOKEN = obj.getfeedToken() 

        self.token="nse_cm|26000&nse_cm|26009&nse_cm|1130&nse_cm|11483&nse_cm|4963&nse_cm|1922&nse_cm|2885&nse_cm|1594&nse_cm|1333&nse_cm|1330&nse_cm|11536&nse_cm|1394&nse_cm|1660"  
        self.task="mw"
        self.ss = SmartWebSocket(FEED_TOKEN, CLIENT_CODE)

    def setupUi(self, Canis):
        Canis.setObjectName("Canis")
        Canis.setWindowModality(QtCore.Qt.NonModal)
        Canis.resize(710, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Canis.sizePolicy().hasHeightForWidth())
        Canis.setSizePolicy(sizePolicy)
        Canis.setMinimumSize(QtCore.QSize(710, 720))
        Canis.setMaximumSize(QtCore.QSize(710, 720))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 79, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(156, 167, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        Canis.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        Canis.setFont(font)

        self.stockData = QtWidgets.QTabWidget(Canis)
        self.stockData.setGeometry(QtCore.QRect(10, 130, 691, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockData.sizePolicy().hasHeightForWidth())
        self.stockData.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(237, 237, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 237, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.stockData.setPalette(palette)
        self.stockData.setFocusPolicy(QtCore.Qt.TabFocus)
        self.stockData.setTabPosition(QtWidgets.QTabWidget.North)
        self.stockData.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.stockData.setIconSize(QtCore.QSize(40, 20))
        self.stockData.setElideMode(QtCore.Qt.ElideMiddle)
        self.stockData.setUsesScrollButtons(False)
        self.stockData.setObjectName("stockData")

        self.niftyTable = QtWidgets.QWidget()
        self.niftyTable.setObjectName("niftyTable")

        self.niftyStockPrices = QtWidgets.QTableWidget(self.niftyTable)
        self.niftyStockPrices.setGeometry(QtCore.QRect(10, 20, 661, 491))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.niftyStockPrices.setPalette(palette)
        # self.niftyStockPrices.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.niftyStockPrices.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.niftyStockPrices.setTextElideMode(QtCore.Qt.ElideNone)
        self.niftyStockPrices.setShowGrid(True)
        self.niftyStockPrices.setObjectName("niftyStockPrices")
        self.niftyStockPrices.setColumnCount(5)
        self.niftyStockPrices.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.niftyStockPrices.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.niftyStockPrices.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.niftyStockPrices.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.niftyStockPrices.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.niftyStockPrices.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.niftyStockPrices.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.niftyStockPrices.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.niftyStockPrices.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.niftyStockPrices.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.niftyStockPrices.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setItem(8, 4, item)
        self.stockData.addTab(self.niftyTable, "")

        self.bankniftyTable = QtWidgets.QWidget()
        self.bankniftyTable.setObjectName("bankniftyTable")

        self.bankniftyStockPrices = QtWidgets.QTableWidget(self.bankniftyTable)
        self.bankniftyStockPrices.setGeometry(QtCore.QRect(10, 20, 661, 491))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.bankniftyStockPrices.setPalette(palette)
        # self.bankniftyStockPrices.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.bankniftyStockPrices.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.bankniftyStockPrices.setTextElideMode(QtCore.Qt.ElideNone)
        self.bankniftyStockPrices.setShowGrid(True)
        self.bankniftyStockPrices.setObjectName("bankniftyStockPrices")
        self.bankniftyStockPrices.setColumnCount(5)
        self.bankniftyStockPrices.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bankniftyStockPrices.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bankniftyStockPrices.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bankniftyStockPrices.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bankniftyStockPrices.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bankniftyStockPrices.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bankniftyStockPrices.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bankniftyStockPrices.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bankniftyStockPrices.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bankniftyStockPrices.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bankniftyStockPrices.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setItem(11, 4, item)

        self.stockData.addTab(self.bankniftyTable, "")

        self.startMarket = QtWidgets.QRadioButton(Canis)
        self.startMarket.setGeometry(QtCore.QRect(580, 30, 81, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startMarket.sizePolicy().hasHeightForWidth())
        self.startMarket.setSizePolicy(sizePolicy)
        self.startMarket.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startMarket.setObjectName("startMarket")

        self.bankniftyPriceDisplay = QtWidgets.QFrame(Canis)
        self.bankniftyPriceDisplay.setEnabled(True)
        self.bankniftyPriceDisplay.setGeometry(QtCore.QRect(300, 30, 240, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.bankniftyPriceDisplay.setPalette(palette)
        self.bankniftyPriceDisplay.setInputMethodHints(QtCore.Qt.ImhNone)
        self.bankniftyPriceDisplay.setFrameShape(QtWidgets.QFrame.Panel)
        self.bankniftyPriceDisplay.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.bankniftyPriceDisplay.setObjectName("bankniftyPriceDisplay")

        self.bankNifty = QtWidgets.QLabel(self.bankniftyPriceDisplay)
        self.bankNifty.setGeometry(QtCore.QRect(10, 0, 130, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bankNifty.setFont(font)
        self.bankNifty.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.bankNifty.setObjectName("bankNifty")

        self.bankniftyPrice = QtWidgets.QLabel(self.bankniftyPriceDisplay)
        self.bankniftyPrice.setGeometry(QtCore.QRect(130, 0, 110, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bankniftyPrice.setFont(font)
        self.bankniftyPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.bankniftyPrice.setObjectName("bankniftyPrice")

        self.niftyPriceDisplay = QtWidgets.QFrame(Canis)
        self.niftyPriceDisplay.setGeometry(QtCore.QRect(30, 30, 231, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.niftyPriceDisplay.sizePolicy().hasHeightForWidth())
        self.niftyPriceDisplay.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.niftyPriceDisplay.setPalette(palette)
        self.niftyPriceDisplay.setFrameShape(QtWidgets.QFrame.Panel)
        self.niftyPriceDisplay.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.niftyPriceDisplay.setObjectName("niftyPriceDisplay")

        self.nifty = QtWidgets.QLabel(self.niftyPriceDisplay)
        self.nifty.setGeometry(QtCore.QRect(10, 0, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nifty.setFont(font)
        self.nifty.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.nifty.setObjectName("nifty")

        self.niftyPrice = QtWidgets.QLabel(self.niftyPriceDisplay)
        self.niftyPrice.setGeometry(QtCore.QRect(100, 0, 110, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.niftyPrice.setFont(font)
        self.niftyPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.niftyPrice.setObjectName("niftyPrice")

        self.stopMarket = QtWidgets.QRadioButton(Canis)
        self.stopMarket.setGeometry(QtCore.QRect(580, 70, 81, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopMarket.sizePolicy().hasHeightForWidth())
        self.stopMarket.setSizePolicy(sizePolicy)
        self.stopMarket.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopMarket.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stopMarket.setObjectName("stopMarket")

        self.retranslateUi(Canis)
        self.stockData.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Canis)

    def retranslateUi(self, Canis):
        self._translate = QtCore.QCoreApplication.translate
        Canis.setWindowTitle(self._translate("Canis", "Form"))
        item = self.niftyStockPrices.verticalHeaderItem(0)
        item.setText(self._translate("Canis", "1"))
        item = self.niftyStockPrices.verticalHeaderItem(1)
        item.setText(self._translate("Canis", "2"))
        item = self.niftyStockPrices.verticalHeaderItem(2)
        item.setText(self._translate("Canis", "3"))
        item = self.niftyStockPrices.verticalHeaderItem(3)
        item.setText(self._translate("Canis", "4"))
        item = self.niftyStockPrices.verticalHeaderItem(4)
        item.setText(self._translate("Canis", "5"))
        item = self.niftyStockPrices.verticalHeaderItem(5)
        item.setText(self._translate("Canis", "6"))
        item = self.niftyStockPrices.verticalHeaderItem(6)
        item.setText(self._translate("Canis", "7"))
        item = self.niftyStockPrices.verticalHeaderItem(7)
        item.setText(self._translate("Canis", "8"))
        item = self.niftyStockPrices.verticalHeaderItem(8)
        item.setText(self._translate("Canis", "10"))
        item = self.niftyStockPrices.horizontalHeaderItem(0)
        item.setText(self._translate("Canis", "Token no."))
        item = self.niftyStockPrices.horizontalHeaderItem(1)
        item.setText(self._translate("Canis", "Stock Name"))
        item = self.niftyStockPrices.horizontalHeaderItem(2)
        item.setText(self._translate("Canis", "Net CNG"))
        item = self.niftyStockPrices.horizontalHeaderItem(3)
        item.setText(self._translate("Canis", "WM (%)"))
        item = self.niftyStockPrices.horizontalHeaderItem(4)
        item.setText(self._translate("Canis", "IC (%)"))
        __sortingEnabled = self.niftyStockPrices.isSortingEnabled()
        self.niftyStockPrices.setSortingEnabled(False)
        item = self.niftyStockPrices.item(0, 0)
        item.setText(self._translate("Canis", "2885"))
        item = self.niftyStockPrices.item(0, 1)
        item.setText(self._translate("Canis", "RELIANCE"))
        item = self.niftyStockPrices.item(0, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(0, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(0, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(1, 0)
        item.setText(self._translate("Canis", "1594"))
        item = self.niftyStockPrices.item(1, 1)
        item.setText(self._translate("Canis", "INFY"))
        item = self.niftyStockPrices.item(1, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(1, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(1, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(2, 0)
        item.setText(self._translate("Canis", "1333"))
        item = self.niftyStockPrices.item(2, 1)
        item.setText(self._translate("Canis", "HDFCBANK"))
        item = self.niftyStockPrices.item(2, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(2, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(2, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(3, 0)
        item.setText(self._translate("Canis", "4963"))
        item = self.niftyStockPrices.item(3, 1)
        item.setText(self._translate("Canis", "ICICIBANK"))
        item = self.niftyStockPrices.item(3, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(3, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(3, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(4, 0)
        item.setText(self._translate("Canis", "1330"))
        item = self.niftyStockPrices.item(4, 1)
        item.setText(self._translate("Canis", "HDFC"))
        item = self.niftyStockPrices.item(4, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(4, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(4, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(5, 0)
        item.setText(self._translate("Canis", "11536"))
        item = self.niftyStockPrices.item(5, 1)
        item.setText(self._translate("Canis", "TCS"))
        item = self.niftyStockPrices.item(5, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(5, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(5, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(6, 0)
        item.setText(self._translate("Canis", "11483"))
        item = self.niftyStockPrices.item(6, 1)
        item.setText(self._translate("Canis", "LT"))
        item = self.niftyStockPrices.item(6, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(6, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(6, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(7, 0)
        item.setText(self._translate("Canis", "1394"))
        item = self.niftyStockPrices.item(7, 1)
        item.setText(self._translate("Canis", "HINDUNILVR"))
        item = self.niftyStockPrices.item(7, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(7, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(7, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(8, 0)
        item.setText(self._translate("Canis", "1660"))
        item = self.niftyStockPrices.item(8, 1)
        item.setText(self._translate("Canis", "ITC"))
        item = self.niftyStockPrices.item(8, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(8, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.niftyStockPrices.item(8, 4)
        item.setText(self._translate("Canis", "0"))
        self.niftyStockPrices.setSortingEnabled(__sortingEnabled)
        
        self.stockData.setTabText(self.stockData.indexOf(self.niftyTable), self._translate("Canis", "NIFTY"))
        item = self.bankniftyStockPrices.verticalHeaderItem(0)
        item.setText(self._translate("Canis", "1"))
        item = self.bankniftyStockPrices.verticalHeaderItem(1)
        item.setText(self._translate("Canis", "2"))
        item = self.bankniftyStockPrices.verticalHeaderItem(2)
        item.setText(self._translate("Canis", "3"))
        item = self.bankniftyStockPrices.verticalHeaderItem(3)
        item.setText(self._translate("Canis", "4"))
        item = self.bankniftyStockPrices.verticalHeaderItem(4)
        item.setText(self._translate("Canis", "5"))
        item = self.bankniftyStockPrices.verticalHeaderItem(5)
        item.setText(self._translate("Canis", "6"))
        item = self.bankniftyStockPrices.verticalHeaderItem(6)
        item.setText(self._translate("Canis", "7"))
        item = self.bankniftyStockPrices.verticalHeaderItem(7)
        item.setText(self._translate("Canis", "8"))
        item = self.bankniftyStockPrices.verticalHeaderItem(8)
        item.setText(self._translate("Canis", "10"))
        item = self.bankniftyStockPrices.verticalHeaderItem(9)
        item.setText(self._translate("Canis", "11"))
        item = self.bankniftyStockPrices.verticalHeaderItem(10)
        item.setText(self._translate("Canis", "12"))
        item = self.bankniftyStockPrices.verticalHeaderItem(11)
        item.setText(self._translate("Canis", "13"))
        item = self.bankniftyStockPrices.horizontalHeaderItem(0)
        item.setText(self._translate("Canis", "Token no."))
        item = self.bankniftyStockPrices.horizontalHeaderItem(1)
        item.setText(self._translate("Canis", "Stock Name"))
        item = self.bankniftyStockPrices.horizontalHeaderItem(2)
        item.setText(self._translate("Canis", "Net CNG"))
        item = self.bankniftyStockPrices.horizontalHeaderItem(3)
        item.setText(self._translate("Canis", "WM (%)"))
        item = self.bankniftyStockPrices.horizontalHeaderItem(4)
        item.setText(self._translate("Canis", "IC (%)"))
        __sortingEnabled = self.bankniftyStockPrices.isSortingEnabled()
        self.bankniftyStockPrices.setSortingEnabled(False)
        item = self.bankniftyStockPrices.item(0, 0)
        item.setText(self._translate("Canis", "1333"))
        item = self.bankniftyStockPrices.item(0, 1)
        item.setText(self._translate("Canis", "HDFCBANK"))
        item = self.bankniftyStockPrices.item(0, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(0, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(0, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(1, 0)
        item.setText(self._translate("Canis", "4963"))
        item = self.bankniftyStockPrices.item(1, 1)
        item.setText(self._translate("Canis", "ICICIBANK"))
        item = self.bankniftyStockPrices.item(1, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(1, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(1, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(2, 0)
        item.setText(self._translate("Canis", "1922"))
        item = self.bankniftyStockPrices.item(2, 1)
        item.setText(self._translate("Canis", "KOTAKBANK"))
        item = self.bankniftyStockPrices.item(2, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(2, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(2, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(3, 0)
        item.setText(self._translate("Canis", "5900"))
        item = self.bankniftyStockPrices.item(3, 1)
        item.setText(self._translate("Canis", "AXISBANK"))
        item = self.bankniftyStockPrices.item(3, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(3, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(3, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(4, 0)
        item.setText(self._translate("Canis", "3045"))
        item = self.bankniftyStockPrices.item(4, 1)
        item.setText(self._translate("Canis", "SBIN"))
        item = self.bankniftyStockPrices.item(4, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(4, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(4, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(5, 0)
        item.setText(self._translate("Canis", "5258"))
        item = self.bankniftyStockPrices.item(5, 1)
        item.setText(self._translate("Canis", "INDUSINDBK"))
        item = self.bankniftyStockPrices.item(5, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(5, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(5, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(6, 0)
        item.setText(self._translate("Canis", "21238"))
        item = self.bankniftyStockPrices.item(6, 1)
        item.setText(self._translate("Canis", "AUBANK"))
        item = self.bankniftyStockPrices.item(6, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(6, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(6, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(7, 0)
        item.setText(self._translate("Canis", "2263"))
        item = self.bankniftyStockPrices.item(7, 1)
        item.setText(self._translate("Canis", "BANDHANBNK"))
        item = self.bankniftyStockPrices.item(7, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(7, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(7, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(8, 0)
        item.setText(self._translate("Canis", "1023"))
        item = self.bankniftyStockPrices.item(8, 1)
        item.setText(self._translate("Canis", "FEDERALBNK"))
        item = self.bankniftyStockPrices.item(8, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(8, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(8, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(9, 0)
        item.setText(self._translate("Canis", "11184"))
        item = self.bankniftyStockPrices.item(9, 1)
        item.setText(self._translate("Canis", "IDFCFIRSTB"))
        item = self.bankniftyStockPrices.item(9, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(9, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(9, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(10, 0)
        item.setText(self._translate("Canis", "10666"))
        item = self.bankniftyStockPrices.item(10, 1)
        item.setText(self._translate("Canis", "PNB"))
        item = self.bankniftyStockPrices.item(10, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(10, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(10, 4)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(11, 0)
        item.setText(self._translate("Canis", "18391"))
        item = self.bankniftyStockPrices.item(11, 1)
        item.setText(self._translate("Canis", "RBLBANK"))
        item = self.bankniftyStockPrices.item(11, 2)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(11, 3)
        item.setText(self._translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(11, 4)
        item.setText(self._translate("Canis", "0"))
        self.bankniftyStockPrices.setSortingEnabled(__sortingEnabled)
        self.stockData.setTabText(self.stockData.indexOf(self.bankniftyTable), self._translate("Canis", "BANK NIFTY"))
        self.startMarket.setText(self._translate("Canis", "START "))
        self.bankNifty.setText(self._translate("Canis", "BANK NIFTY :"))
        self.bankniftyPrice.setText(self._translate("Canis", "0"))
        self.nifty.setText(self._translate("Canis", "NIFTY :"))
        self.niftyPrice.setText(self._translate("Canis", "0"))
        self.stopMarket.setText(self._translate("Canis", "STOP"))

        self.startMarket.clicked.connect(self.webSocketCall)
        self.stopMarket.clicked.connect(self.webSocketCall)

    def threadMsg(self,message):        
        self.t2 = thread_with_trace(target = thread_with_trace.readData(self,message,self.niftyStockPrices,self.niftyPrice,self.bankniftyPrice))
        self.t2.start()

    def webSocketLmao(self):
        self.ss._on_open = lambda ws:self.ss.subscribe(self.task,self.token)
        self.ss._on_message = lambda ws,message:self.threadMsg(message)
        # self.ss._on_message = lambda ws,message:self.readData(message)
        self.ss._on_error = lambda ws,error:print(error)
        self.ss._on_close = lambda ws:print("Close")

        self.t1 = thread_with_trace(target = self.ss.connect)
        self.t1.start()

        
    def webSocketCall(self):
        if self.startMarket.isChecked():
            self.webSocketLmao()

        if self.stopMarket.isChecked():
            self.t1.kill()
            self.t2.kill()

    
    # def readData(self,message):
    #     getData(message)
    #     self.data = 'stockData.json'
    #     self.dataList = []
    #     with open(self.data) as fp:
    #         self.dataList = json.load(fp)

    #     self.tableUpdate()

    # def tableUpdate(self):
    #     # print(self.dataList)
    #     rowPosition = self.niftyStockPrices.rowCount()

    #     # print(type(rowPosition))
        
    #     for i in range(rowPosition):
    #         for j in self.dataList:
    #             # print(j)
    #             if j['TK'] == int(self.niftyStockPrices.item(i,0).text()):
    #                 item = self.niftyStockPrices.item(i, 2)
    #                 item.setText(self._translate("Canis", str(j['NETCNG'])))
    #                 item = self.niftyStockPrices.item(i, 3)
    #                 item.setText(self._translate("Canis", str(j['WMN'])))
    #                 item = self.niftyStockPrices.item(i, 4)
    #                 item.setText(self._translate("Canis", str(j['ICN'])))

    #                 self.niftyStockPrices.viewport().update()
                # if j['TK'] == int(self.bankniftyStockPrices.item(i,0).text()):
                #     item = self.bankniftyStockPrices.item(i, 2)
                #     item.setText(self._translate("Canis", str(j['NETCNG'])))
                #     item = self.bankniftyStockPrices.item(i, 3)
                #     item.setText(self._translate("Canis", str(j['WMBN'])))
                #     item = self.bankniftyStockPrices.item(i, 4)
                #     item.setText(self._translate("Canis", str(j['ICB'])))
        # print(rowPosition)
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Canis = QtWidgets.QWidget()
    ui = Ui_Canis()
    ui.setupUi(Canis)
    Canis.show()
    sys.exit(app.exec_())
