import json
import os
from smartapi import SmartWebSocket, SmartConnect
from PyQt5 import QtCore, QtGui, QtWidgets
from dotenv import load_dotenv

import sys
from thread import thread_with_trace
from stockIndices import getData


class Ui_Canis(object):
    def __init__(self):
        load_dotenv()
        CLIENT_CODE=os.getenv('Client_ID')
        PASSWORD=os.getenv('Password')
        API_KEY=os.getenv('API_key')
        self.example = [{'e': 'nse_cm', 'ltp': '1955.20', 'ltq': '2', 'ltt': 'NA', 'name': 'sf', 'tk': '11483'}, {'c': '17757.00', 'cng': '-146.85', 'e': 'nse_cm', 'ltp': '17610', 'ltt': 'NA', 'name': 'sf', 'nc': '-00.827', 'tk': '26000'}, {'c': '37850.85', 'cng': '-313.65', 'e': 'nse_cm', 'ltp': '37537.20', 'ltt': 'NA', 'name': 'sf', 'nc': '-00.8286', 'tk': '26009'}]

        obj=SmartConnect(api_key=API_KEY)
        obj.generateSession(CLIENT_CODE,PASSWORD)
        FEED_TOKEN = obj.getfeedToken() 

        self.token="nse_cm|26000&nse_cm|26009&nse_cm|11483&nse_cm|1594&nse_cm|1922"  
        self.task="mw"
        self.ss = SmartWebSocket(FEED_TOKEN, CLIENT_CODE)

    def setupUi(self, Canis):
        Canis.setObjectName("Canis")
        Canis.setWindowModality(QtCore.Qt.NonModal)
        Canis.resize(710, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Canis.sizePolicy().hasHeightForWidth())
        Canis.setSizePolicy(sizePolicy)
        Canis.setMinimumSize(QtCore.QSize(710, 720))
        Canis.setMaximumSize(QtCore.QSize(710, 720))

        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 79, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(156, 167, 165))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        Canis.setPalette(palette)

        font = QtGui.QFont()
        font.setPointSize(10)
        Canis.setFont(font)

        self.stockData = QtWidgets.QTabWidget(Canis)
        self.stockData.setGeometry(QtCore.QRect(10, 140, 691, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockData.sizePolicy().hasHeightForWidth())
        self.stockData.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(237, 237, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 237, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.stockData.setPalette(palette)
        self.stockData.setTabPosition(QtWidgets.QTabWidget.North)
        self.stockData.setIconSize(QtCore.QSize(40, 20))
        self.stockData.setElideMode(QtCore.Qt.ElideMiddle)
        self.stockData.setUsesScrollButtons(False)
        self.stockData.setObjectName("stockData")

        self.niftyTable = QtWidgets.QWidget()
        self.niftyTable.setObjectName("niftyTable")
        
        self.niftyStockPrices = QtWidgets.QTableWidget(self.niftyTable)
        self.niftyStockPrices.setGeometry(QtCore.QRect(15, 20, 651, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.niftyStockPrices.sizePolicy().hasHeightForWidth())
        self.niftyStockPrices.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 23, 92))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 36, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 44, 44))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.niftyStockPrices.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.niftyStockPrices.setFont(font)
        self.niftyStockPrices.setFocusPolicy(QtCore.Qt.TabFocus)
        self.niftyStockPrices.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.niftyStockPrices.setAcceptDrops(False)
        self.niftyStockPrices.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.niftyStockPrices.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.niftyStockPrices.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.niftyStockPrices.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.niftyStockPrices.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.niftyStockPrices.setGridStyle(QtCore.Qt.SolidLine)
        self.niftyStockPrices.setWordWrap(True)
        self.niftyStockPrices.setObjectName("niftyStockPrices")
        self.niftyStockPrices.setColumnCount(5)
        self.niftyStockPrices.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.niftyStockPrices.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.niftyStockPrices.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.niftyStockPrices.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.niftyStockPrices.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.niftyStockPrices.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.niftyStockPrices.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.niftyStockPrices.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.niftyStockPrices.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.niftyStockPrices.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.niftyStockPrices.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.niftyStockPrices.setItem(0, 4, item)
        self.niftyStockPrices.horizontalHeader().setCascadingSectionResizes(False)

        self.stockData.addTab(self.niftyTable, "")
        self.bankniftyTable = QtWidgets.QWidget()
        self.bankniftyTable.setObjectName("bankniftyTable")

        self.bankniftyStockPrices = QtWidgets.QTableWidget(self.bankniftyTable)
        self.bankniftyStockPrices.setGeometry(QtCore.QRect(15, 20, 651, 491))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.bankniftyStockPrices.setPalette(palette)
        self.bankniftyStockPrices.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.bankniftyStockPrices.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.bankniftyStockPrices.setTextElideMode(QtCore.Qt.ElideNone)
        self.bankniftyStockPrices.setShowGrid(True)
        self.bankniftyStockPrices.setObjectName("bankniftyStockPrices")
        self.bankniftyStockPrices.setColumnCount(5)
        self.bankniftyStockPrices.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.bankniftyStockPrices.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bankniftyStockPrices.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bankniftyStockPrices.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bankniftyStockPrices.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bankniftyStockPrices.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.bankniftyStockPrices.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bankniftyStockPrices.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bankniftyStockPrices.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bankniftyStockPrices.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bankniftyStockPrices.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.bankniftyStockPrices.setItem(0, 4, item)

        self.stockData.addTab(self.bankniftyTable, "")

        self.startMarket = QtWidgets.QRadioButton(Canis)
        self.startMarket.setGeometry(QtCore.QRect(580, 30, 81, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startMarket.sizePolicy().hasHeightForWidth())
        self.startMarket.setSizePolicy(sizePolicy)
        self.startMarket.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startMarket.setObjectName("startMarket")

        self.bankniftyPriceDisplay = QtWidgets.QFrame(Canis)
        self.bankniftyPriceDisplay.setEnabled(True)
        self.bankniftyPriceDisplay.setGeometry(QtCore.QRect(300, 30, 240, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.bankniftyPriceDisplay.setPalette(palette)
        self.bankniftyPriceDisplay.setInputMethodHints(QtCore.Qt.ImhNone)
        self.bankniftyPriceDisplay.setFrameShape(QtWidgets.QFrame.Panel)
        self.bankniftyPriceDisplay.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.bankniftyPriceDisplay.setObjectName("bankniftyPriceDisplay")

        self.bankNifty = QtWidgets.QLabel(self.bankniftyPriceDisplay)
        self.bankNifty.setGeometry(QtCore.QRect(10, 0, 130, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bankNifty.setFont(font)
        self.bankNifty.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.bankNifty.setObjectName("bankNifty")

        self.bankniftyPrice = QtWidgets.QLabel(self.bankniftyPriceDisplay)
        self.bankniftyPrice.setGeometry(QtCore.QRect(130, 0, 110, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bankniftyPrice.setFont(font)
        self.bankniftyPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.bankniftyPrice.setObjectName("bankniftyPrice")

        self.niftyPriceDisplay = QtWidgets.QFrame(Canis)
        self.niftyPriceDisplay.setGeometry(QtCore.QRect(30, 30, 231, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.niftyPriceDisplay.sizePolicy().hasHeightForWidth())
        self.niftyPriceDisplay.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(77, 77, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 214, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.niftyPriceDisplay.setPalette(palette)
        self.niftyPriceDisplay.setFrameShape(QtWidgets.QFrame.Panel)
        self.niftyPriceDisplay.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.niftyPriceDisplay.setObjectName("niftyPriceDisplay")

        self.nifty = QtWidgets.QLabel(self.niftyPriceDisplay)
        self.nifty.setGeometry(QtCore.QRect(10, 0, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nifty.setFont(font)
        self.nifty.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.nifty.setObjectName("nifty")

        self.niftyPrice = QtWidgets.QLabel(self.niftyPriceDisplay)
        self.niftyPrice.setGeometry(QtCore.QRect(100, 0, 110, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.niftyPrice.setFont(font)
        self.niftyPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.niftyPrice.setObjectName("niftyPrice")

        self.stopMarket = QtWidgets.QRadioButton(Canis)
        self.stopMarket.setGeometry(QtCore.QRect(580, 70, 81, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopMarket.sizePolicy().hasHeightForWidth())
        self.stopMarket.setSizePolicy(sizePolicy)
        self.stopMarket.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopMarket.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stopMarket.setObjectName("stopMarket")

        self.retranslateUi(Canis)
        self.stockData.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Canis)

    def retranslateUi(self, Canis):
        _translate = QtCore.QCoreApplication.translate
        Canis.setWindowTitle(_translate("Canis", "Form"))
        item = self.niftyStockPrices.verticalHeaderItem(0)
        item.setText(_translate("Canis", "1"))
        item = self.niftyStockPrices.horizontalHeaderItem(0)
        item.setText(_translate("Canis", "Token no."))
        item = self.niftyStockPrices.horizontalHeaderItem(1)
        item.setText(_translate("Canis", "Stock Name"))
        item = self.niftyStockPrices.horizontalHeaderItem(2)
        item.setText(_translate("Canis", "Net CNG"))
        item = self.niftyStockPrices.horizontalHeaderItem(3)
        item.setText(_translate("Canis", "WM (%)"))
        item = self.niftyStockPrices.horizontalHeaderItem(4)
        item.setText(_translate("Canis", "IC (%)"))
        __sortingEnabled = self.niftyStockPrices.isSortingEnabled()
        self.niftyStockPrices.setSortingEnabled(False)
        item = self.niftyStockPrices.item(0, 0)
        item.setText(_translate("Canis", "0"))
        item = self.niftyStockPrices.item(0, 1)
        item.setText(_translate("Canis", "dummy"))
        item = self.niftyStockPrices.item(0, 2)
        item.setText(_translate("Canis", "0"))
        item = self.niftyStockPrices.item(0, 3)
        item.setText(_translate("Canis", "0"))
        item = self.niftyStockPrices.item(0, 4)
        item.setText(_translate("Canis", "0"))
        self.niftyStockPrices.setSortingEnabled(__sortingEnabled)
        self.stockData.setTabText(self.stockData.indexOf(self.niftyTable), _translate("Canis", "NIFTY"))
        item = self.bankniftyStockPrices.verticalHeaderItem(0)
        item.setText(_translate("Canis", "1"))
        item = self.bankniftyStockPrices.horizontalHeaderItem(0)
        item.setText(_translate("Canis", "Token no."))
        item = self.bankniftyStockPrices.horizontalHeaderItem(1)
        item.setText(_translate("Canis", "Stock Name"))
        item = self.bankniftyStockPrices.horizontalHeaderItem(2)
        item.setText(_translate("Canis", "Net CNG"))
        item = self.bankniftyStockPrices.horizontalHeaderItem(3)
        item.setText(_translate("Canis", "WM (%)"))
        item = self.bankniftyStockPrices.horizontalHeaderItem(4)
        item.setText(_translate("Canis", "IC (%)"))
        __sortingEnabled = self.bankniftyStockPrices.isSortingEnabled()
        self.bankniftyStockPrices.setSortingEnabled(False)
        item = self.bankniftyStockPrices.item(0, 0)
        item.setText(_translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(0, 1)
        item.setText(_translate("Canis", "dummy"))
        item = self.bankniftyStockPrices.item(0, 2)
        item.setText(_translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(0, 3)
        item.setText(_translate("Canis", "0"))
        item = self.bankniftyStockPrices.item(0, 4)
        item.setText(_translate("Canis", "0"))
        self.bankniftyStockPrices.setSortingEnabled(__sortingEnabled)
        self.stockData.setTabText(self.stockData.indexOf(self.bankniftyTable), _translate("Canis", "BANK NIFTY"))
        self.startMarket.setText(_translate("Canis", "START "))
        self.bankNifty.setText(_translate("Canis", "BANK NIFTY :"))
        self.bankniftyPrice.setText(_translate("Canis", "0"))
        self.nifty.setText(_translate("Canis", "NIFTY :"))
        self.niftyPrice.setText(_translate("Canis", "0"))
        self.stopMarket.setText(_translate("Canis", "STOP"))

        self.startMarket.clicked.connect(self.webSocketCall)
        self.stopMarket.clicked.connect(self.webSocketCall)

        # self.webSocketCall()

    def webSocketLmao(self):
        self.ss._on_open = lambda ws:self.ss.subscribe(self.task,self.token)
        self.ss._on_message = lambda ws,message:self.readData(message)
        self.ss._on_error = lambda ws,error:print(error)
        self.ss._on_close = lambda ws:print("Close")

        self.t1 = thread_with_trace(target = self.ss.connect)
        self.t1.start()

        
    def webSocketCall(self):
        if self.startMarket.isChecked():
            self.webSocketLmao()

        if self.stopMarket.isChecked():
            self.t1.kill()

    def readData(self,message):
        getData(message)
        self.data = 'stockData.json'
        self.dataList = []
        with open(self.data) as fp:
            self.dataList = json.load(fp)

        self.tableUpdate()

    def tableUpdate(self):
        print(self.dataList)
        rowPosition = self.niftyStockPrices.rowCount()
        # print(rowPosition)
        self.niftyStockPrices.insertRow(rowPosition)

        self.niftyStockPrices.setItem(rowPosition , 0, QtWidgets.QTableWidgetItem("0"))
        self.niftyStockPrices.setItem(rowPosition , 1, QtWidgets.QTableWidgetItem("dummy"))
        self.niftyStockPrices.setItem(rowPosition , 2, QtWidgets.QTableWidgetItem("0"))
        self.niftyStockPrices.setItem(rowPosition , 3, QtWidgets.QTableWidgetItem("0"))
        self.niftyStockPrices.setItem(rowPosition , 4, QtWidgets.QTableWidgetItem("0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Canis = QtWidgets.QWidget()
    ui = Ui_Canis()
    ui.setupUi(Canis)
    Canis.show()
    sys.exit(app.exec_())
